spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:db}
    password: ${REDIS_PASSWORD:}

  jackson:
    property-naming-strategy: SNAKE_CASE

auth:
  jwt:
    secret: ${JWT_SECRET_KEY}
    exp:
      access: ${JWT_ACCESS_EXP:7200}
      refresh: ${JWT_REFRESH_EXP:7200}
    header: ${JWT_HEADER:header}
    prefix: ${JWT_PREFIX:prefix}